# Reader tests against the synthetic fixtures in inst/extdata/synthetic/.
# Generated by `data-raw/make_synthetic.R` (deterministic, seed = 42).

fxpath <- function(name) {
  system.file("extdata", "synthetic", name, package = "MetaboSetR",
              mustWork = TRUE)
}

# ---- read_webidq -----------------------------------------------------------

test_that("read_webidq parses the synthetic sample data via text status", {
  cd <- read_webidq(fxpath("sample_conc.xlsx"),
                    fxpath("sample_status.xlsx"),
                    status_method = "text")
  expect_s4_class(cd, "ConcentrationData")
  expect_equal(dim(cd@assay), c(6L, 30L))
  expect_equal(dim(cd@status), c(6L, 30L))
  expect_setequal(unique(as.vector(cd@status)),
                  c("Valid", "< LOD", "< LLOQ", "< threshold", "> ULOQ"))
  expect_equal(cd@sample_meta$kit_id,
               c(rep("KIT01", 3L), rep("KIT02", 3L)))
  expect_length(cd@metabolite_names, 30L)
  # Specific spec'd cell from make_synthetic.R: row 3, col 25 is "> ULOQ".
  expect_equal(unname(cd@status[3L, 25L]), "> ULOQ")
  expect_equal(unname(cd@status[1L, 5L]), "< LOD")
})

test_that("read_webidq color fallback recovers the same status matrix", {
  cd_text <- read_webidq(fxpath("sample_conc.xlsx"),
                         fxpath("sample_status.xlsx"),
                         status_method = "text")
  cd_color <- read_webidq(fxpath("sample_conc.xlsx"),
                          status_method = "color")
  expect_equal(unname(cd_color@status), unname(cd_text@status))
})

test_that("read_webidq errors when status_method='text' but no status_file", {
  expect_error(
    read_webidq(fxpath("sample_conc.xlsx"), status_method = "text"),
    "status_file is required"
  )
})

test_that(".extract_kit_id is NA-tolerant (decisions.md #51)", {
  # Earlier versions broke with `NAs are not allowed in subscripted
  # assignments` when any submission name was NA, because the regexpr()
  # result propagated NA into the logical subscript.
  out <- MetaboSetR:::.extract_kit_id(
    c("PROJ-X-KIT01", NA_character_, "no kit token here", "PROJ-X-KIT02"))
  expect_equal(out, c("KIT01", NA_character_, NA_character_, "KIT02"))

  # All-NA input must not error and must return all-NA output.
  expect_equal(MetaboSetR:::.extract_kit_id(rep(NA_character_, 3L)),
               rep(NA_character_, 3L))
})

test_that(".is_padding_row uses Sample identification as the marker (decisions.md #52)", {
  META <- MetaboSetR:::.WEBIDQ_META_COLS
  df <- data.frame(matrix(NA_character_, nrow = 4L,
                          ncol = length(META) + 2L),
                   stringsAsFactors = FALSE)
  names(df) <- c(META, "C0", "C2")
  # Row 1: all NA (incl. Sample identification) -> padding.
  # Row 2: Sample identification set -> real row, even though Collection
  #        date is NA (vendor often leaves that blank on real rows).
  # Row 3: every meta but Material is NA — this is the QC-tail pattern;
  #        Sample identification NA -> still padding.
  # Row 4: every meta filled -> real row.
  df[1L, ] <- NA
  df[2L, "Sample identification"] <- "S1"
  df[3L, "Material"] <- "Plasma"
  df[4L, META] <- as.list(rep("x", length(META)))
  expect_equal(MetaboSetR:::.is_padding_row(df[["Sample identification"]]),
               c(TRUE, FALSE, TRUE, FALSE))
})

test_that(".kit_id_from_filename pulls KIT token (decisions.md #51)", {
  expect_equal(
    MetaboSetR:::.kit_id_from_filename("OMICS_thresholds_KIT01.xlsx"),
    "KIT01"
  )
  expect_equal(
    MetaboSetR:::.kit_id_from_filename("/some/path/x_KIT12_y.xlsx"),
    "KIT12"
  )
  expect_error(
    MetaboSetR:::.kit_id_from_filename("no_kit_token.xlsx"),
    "Could not find a `KIT"
  )
})

test_that("read_webidq does not depend on sheet names (decisions.md #50)", {
  # Sanity check: the synthetic fixtures are deliberately built with
  # different sheet names across conc and status files so that this test
  # actually exercises the "sheet name is not validated" guarantee.
  conc_sheets   <- readxl::excel_sheets(fxpath("sample_conc.xlsx"))
  status_sheets <- readxl::excel_sheets(fxpath("sample_status.xlsx"))
  expect_length(conc_sheets, 1L)
  expect_length(status_sheets, 1L)
  expect_false(identical(conc_sheets, status_sheets))

  # The reader still succeeds despite the divergence.
  cd <- read_webidq(fxpath("sample_conc.xlsx"),
                    fxpath("sample_status.xlsx"),
                    status_method = "text")
  expect_s4_class(cd, "ConcentrationData")
})

# ---- read_webidq_qc --------------------------------------------------------

test_that("read_webidq_qc parses the synthetic QC data", {
  qc <- read_webidq_qc(fxpath("qc_conc.xlsx"),
                       fxpath("qc_status.xlsx"),
                       status_method = "text")
  expect_s4_class(qc, "QCData")
  expect_equal(dim(qc@assay), c(6L, 30L))
  expect_equal(qc@sample_meta$kit_id,
               c(rep("KIT01", 3L), rep("KIT02", 3L)))
  # The two LOD cells we deliberately set in make_synthetic.R.
  expect_equal(unname(qc@status[1L, 25L]), "< LOD")
  expect_equal(unname(qc@status[4L, 26L]), "< LOD")
})

# ---- read_thresholds -------------------------------------------------------

test_that("read_thresholds combines per-kit files into one ThresholdData", {
  td <- read_thresholds(c(fxpath("thresholds_KIT01.xlsx"),
                          fxpath("thresholds_KIT02.xlsx")))
  expect_s4_class(td, "ThresholdData")
  expect_equal(td@kit_ids, c("KIT01", "KIT02"))
  expect_equal(dim(td@lod), c(2L, 30L))
  expect_equal(dim(td@lloq), c(2L, 30L))
  expect_equal(dim(td@uloq), c(2L, 30L))
  # Column 25 is intentionally NA in lloq/uloq for KIT01 (lipid-NA mimic).
  expect_true(is.na(td@lloq[1L, 25L]))
  expect_true(is.na(td@uloq[1L, 25L]))
  # No NAs in LOD.
  expect_false(any(is.na(td@lod)))
  expect_equal(length(td@metabolite_names), 30L)
})

test_that("read_thresholds errors on empty input", {
  expect_error(read_thresholds(character(0)),
               "at least one path")
})

# ---- name resolution -------------------------------------------------------

test_that(".resolve_metabolite_names accepts canonical short names", {
  out <- MetaboSetR:::.resolve_metabolite_names(c("Arg", "Cys"))
  expect_equal(out, c("Arg", "Cys"))
})

test_that(".resolve_metabolite_names maps fullname -> shortname", {
  out <- MetaboSetR:::.resolve_metabolite_names(
    c("Arginine", "Cysteine"))
  expect_equal(out, c("Arg", "Cys"))
})

test_that(".resolve_metabolite_names errors with helpful message on unknown", {
  expect_error(
    MetaboSetR:::.resolve_metabolite_names(c("Arg", "Banana")),
    "Could not resolve"
  )
})

test_that(".resolve_metabolite_names honors user synonyms", {
  out <- MetaboSetR:::.resolve_metabolite_names(
    c("Arg", "MyCystName"),
    synonyms = c("MyCystName" = "Cys"))
  expect_equal(out, c("Arg", "Cys"))
})
